### PR TITLE
Small fixes for xorg-server

### LINKED ISSUE #117: getentropy() unimplemented
During testing on managarm, the following program required `getentropy()`

- `wget`, when fetching `https://` links

### PR DESCRIPTION
**Pull request by Dennisbonke**
This PR fixes some small bugs that the compilation of xorg-server on managarm found.
Furthermore, it implements some functions that are required at runtime for `Xwayland`. It also adds `getentropy()`, and the corresponding syscall for managarm.

Blocked on managarm/managarm#195
Closes #117

### CODE REVIEW

File: sysdeps/managarm/generic/file.cpp [hunk 1]
```diff
@@ -4088,5 +4089,20 @@ int sys_utimensat(int dirfd, const char *pathname, const struct timespec times[2
...
+	SignalGuard sguard;
+	uint8_t buf[length];
+	size_t size;
+
+	if(length > 256)
+		return EIO;
+
+	HEL_CHECK(helGetRandomBytes(buf, length, &size));
+
+    memcpy(buffer, buf, size);
```
Comment (avdgrinten) [inline sysdeps/managarm/generic/file.cpp:4102]: Here we have an issue since `helGetRandomBytes` might return fewer than `length` bytes, while `getentropy` is supposed to return exactly `length` bytes. We also do not need `buf`. Suggestion:

```suggestion
	auto p = reinterpret_cast<char *>(buffer);
	size_t n = 0;
	while(n < length) {
		size_t chunk;
		HEL_CHECK(helGetRandomBytes(p + n, length - n, &chunk));
		n += chunk;
	}
```
