### PR TITLE
Symbol versioning support

### LINKED ISSUE #1208: Symbol versioning is unsupported
This breaks libpci and lspci for example, because we end up calling the older version of `pci_filter_init` (`pci_filter_init@LIBPCI_3.0`) and the newer version of `pci_filter_match` (`pci_filter_match@LIBPCI_3.8`), which causes some devices to be filtered out incorrectly. I assume which versions get called depends on the symbol hash table.

### PR DESCRIPTION
**Pull request by qookei**
There's some minor TODOs left in the code (handling weak versions and figuring out what to do about VERDEF dependency names), but this is sufficient to fix #1208, and the TODOs aren't a problem when booting Managarm (which has plenty of libraries with versioned symbols).

Closes #1208.

### CODE REVIEW

File: options/rtld/generic/linker.cpp [hunk 1]
```diff
@@ -795,6 +817,167 @@ void ObjectRepository::_parseDynamic(SharedObject *object) {
 	}
 }
 
+void ObjectRepository::_parseVerdef(SharedObject *object) {
+	if(!object->versionDefinitionTableOffset) {
+		if(verbose)
+			mlibc::infoLogger()
+				<< "mlibc: Object " << object->name
+				<< " defines no versions" << frg::endlog;
+		return;
```
Comment (Geertiebear) [inline options/rtld/generic/linker.cpp:826]: What happens in this case? Is an object still able to be resolved even if it doesn't have a DT_VERDEF?

Comment (qookei) [reply options/rtld/generic/linker.cpp:826]: If an object defines no versions but was supposed to, the dependent will error out in `_parseVerneed` on line 965.

Comment (qookei) [reply options/rtld/generic/linker.cpp:826]: If it defines no version and no one wants any versions from it, nothing special happens.

File: options/rtld/generic/linker.cpp [hunk 2]
```diff
@@ -795,6 +816,163 @@ void ObjectRepository::_parseDynamic(SharedObject *object) {
...
+		__ensure(!(def.vd_flags & ~VER_FLG_BASE));
+
+		// TODO(qookie): Figure out what to do about VERDEF dependency names.
+		// They don't make much sense to me, and it seems to work if we just ignore them.
+		elf_verdaux aux;
+		memcpy(&aux, reinterpret_cast<void *>(address + def.vd_aux), sizeof(elf_verdaux));
+
+		const char *name =
+			static_cast<const char *>(
+				reinterpret_cast<void *>(
```
Comment (64) [inline options/rtld/generic/linker.cpp:856]: Can't you reinterpret_cast directly to `const char *`?

File: options/rtld/generic/linker.cpp [hunk 3]
```diff
@@ -795,6 +816,163 @@ void ObjectRepository::_parseDynamic(SharedObject *object) {
...
+
+	for(size_t i = 0; i < object->versionRequirementCount; i++) {
+		elf_verneed need;
+		memcpy(&need, reinterpret_cast<void *>(address), sizeof(elf_verneed));
+
+		// Required by spec.
+		__ensure(need.vn_version == 1);
+
+		frg::string_view file =
+			static_cast<const char *>(
```
Comment (64) [inline options/rtld/generic/linker.cpp:902]: likewise

File: options/rtld/generic/linker.cpp [hunk 4]
```diff
@@ -795,6 +816,163 @@ void ObjectRepository::_parseDynamic(SharedObject *object) {
...
+					+ object->stringTableOffset + need.vn_file));
+
+		// Figure out the target object from file
+		SharedObject *target = nullptr;
+		for(auto dep : object->dependencies) {
+			if(verbose)
+				mlibc::infoLogger()
+					<< "mlibc: Trying " << dep->name << " (SONAME: "
+					<< dep->soName << ") to satisfy " << file << frg::endlog;
+			if(dep->name == file || (dep->soName && dep->soName == file)) {
```
Comment (64) [inline options/rtld/generic/linker.cpp:914]: Looking at `findLoadedObject`, we _only_ compare against SONAME. Is the `dep->name == file` needed? Not a big deal but it would be good to understand what the correct behaviour is in both cases

File: options/rtld/generic/linker.cpp [hunk 5]
```diff
@@ -795,6 +816,163 @@ void ObjectRepository::_parseDynamic(SharedObject *object) {
...
+				<< " version(s) from DSO "
+				<< file << frg::endlog;
+
+		uintptr_t auxAddr = address + need.vn_aux;
+		for(size_t j = 0; j < need.vn_cnt; j++) {
+			elf_vernaux aux;
+			memcpy(&aux, reinterpret_cast<void *>(auxAddr), sizeof(elf_vernaux));
+
+			const char *name =
+				static_cast<const char *>(
```
Comment (64) [inline options/rtld/generic/linker.cpp:942]: likewise

File: options/rtld/generic/linker.cpp [hunk 6]
```diff
@@ -1044,16 +1049,74 @@ SharedObject::SharedObject(const char *name, const char *path,
 			frg::string<MemoryAllocator> { path, getAllocator() },
 			is_main_object, localScope, object_rts) {}
 
+frg::tuple<ObjectSymbol, SymbolVersion> SharedObject::getSymbolByIndex(size_t index) {
+	SymbolVersion ver{1}; // If we don't have any version information, treat all symbols as global.
+	ObjectSymbol sym{
+		this,
+		reinterpret_cast<elf_sym *>(
```
Comment (64) [inline options/rtld/generic/linker.cpp:1056]: likewise (multiple reinterpret_cast)

**Review by 64 — COMMENTED** [review]
LGTM with a few nits

File: options/rtld/generic/linker.cpp (hunk 2 above)
Comment (qookei) [reply options/rtld/generic/linker.cpp:856]: That's true. For some reason I thought you could only `reinterpret_cast` integers into `void *`...

Comment (64) [reply options/rtld/generic/linker.cpp:856]: I believe that's true of `static_cast`

File: options/rtld/generic/linker.cpp (hunk 4 above)
Comment (qookei) [reply options/rtld/generic/linker.cpp:914]: glibc matches both the SONAME and the file name of the object (although in the opposite order compared us AFAICU?). Without checking the file name our test case doesn't pass, since it doesn't have a SONAME (glibc loads it fine).

**Review by 64 — APPROVED** [review]

**Review by Dennisbonke — APPROVED** [review]
LGTM
