### PR TITLE
sysdeps/managarm: Implement sys_mknodat

### LINKED ISSUE #94: mknod() unimplemented
While testing managarm, the following program from `coreutils` crashed on the `mknod()` function being unimplemented

- `mknod`

### PR DESCRIPTION
**Pull request by Dennisbonke**
This PR is the mlibc counterpart of managarm/managarm#248 and provides an implementation of `sys_mknodat()` for managarm, wires `mknod()` to `mknodat()`, improves error handling in some managarm sysdeps and adds a string for ENOSPC to `strerror()`.

Blocked on and to be merged shortly after managarm/managarm#248
Fixes #94

### CODE REVIEW

File: sysdeps/managarm/generic/file.cpp [hunk 1]
```diff
@@ -3174,6 +3176,8 @@ int sys_openat(int dirfd, const char *path, int flags, int *fd) {
 	}else if(resp.error() == managarm::posix::Errors::ILLEGAL_OPERATION_TARGET) {
 		mlibc::infoLogger() << "\e[31mmlibc: openat unimplemented for this file " << path << "\e[39m" << frg::endlog;
 		return EINVAL;
+	}else if(resp.error() == managarm::posix::Errors::SPECIAL_DEVICE) {
```
Comment (avdgrinten) [inline sysdeps/managarm/generic/file.cpp:3179]: Didn't we rename this?

**Review by avdgrinten — APPROVED** [review]
LGTM now.
