### PR TITLE
implement gethostbyname() and a getaddrinfo() fix

### LINKED ISSUE #90: gethostbyname() unimplemented
With the recent addition of tcp to managarm, it has become clear that we are lacking in name resolution. One major example is `gethostbyname()`, required by at least  `lynx` and `syslogd` from my initial testing. We should strive to implement this as soon as possible

### PR DESCRIPTION
**Pull request by Geertiebear**
Fixes #90 . Imo the code is a bit ugly but I didn't see a way to make it substantially prettier. Let me know if I missed something. ``gethostbyname()`` was tested with sysklogd on managarm and seems to work, along with my own testing of the function.

### CODE REVIEW

File: options/posix/generic/netdb-stubs.cpp [hunk 1]
```diff
@@ -81,6 +81,7 @@ int getaddrinfo(const char *__restrict node, const char *__restrict service,
 		out[i].ai.ai_addr = (struct sockaddr *) &out[i].sa;
 		out[i].ai.ai_canonname = canon;
 		out[i].ai.ai_next = NULL;
+		if (i) out[i].ai.ai_next = &out[i - 1].ai;
```
Comment (avdgrinten) [inline options/posix/generic/netdb-stubs.cpp:84]: mlibc's coding style puts one-line `if` cases onto a separate line.

File: options/posix/generic/netdb-stubs.cpp [hunk 2]
```diff
@@ -125,9 +125,78 @@ struct netent *getnetent(void) {
...
-struct hostent *gethostbyname(const char *) {
-	__ensure(!"gethostbyname() not implemented");
-	__builtin_unreachable();
+struct hostent *gethostbyname(const char *name) {
+	if (!name) {
+		h_errno = HOST_NOT_FOUND;
+		return NULL;
+	}
+
+	struct mlibc::dns_addr_buf buf[NAME_MAX];
```
Comment (avdgrinten) [inline options/posix/generic/netdb-stubs.cpp:135]: This looks strange: it's a large array of moderately-sized structs. Doesn't this require huge amounts of (stack) space?
